runtime: python39
instance_class: F2

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "lucid-diode-452919-p1-e5138e5e4227.json"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5

inbound_services:
  - warmup
